### ISSUE TITLE
Notion app don't save changes

### ISSUE THREAD

**Issue by xzavrel** [sysdrum/notion-app#8]
Hi, I use notion-app for Linux for a while. Since some time I have an issue that not everything I do in the app is saved to notion.
Sometimes it's part of the text, sometimes it's style like bullet list etc. During the changes everything seems to be fine, but when I open the app later the changes are incomplete. A don't have these problems with webapp neither https://github.com/puneetsl/lotion. I have tried to rebuild the app, but that didn't help.

It seems that Reload of the app helps for some time. Do you have an idea how to find out the issue?

Environment: Kubuntu 19.04, kernel 5.0.0.

**Comment by sysdrum** [comment]
@xzavrel When using the app do you go offline? 
If not then I am not sure why there is a sync issue. I will need to know more about what v. Node and chrome your are running.

If so then changes will not sync back to notion.so as there is not offline API calls that can be made once you reconnect to notion.so as they have not setup that up in the WEBAPP front-end so the wrapper can not pass changes in that way. 
When you run Notion.so in Chrome/Firefox it is creating local storage for the data in case you loss connection. The wrapper can not do that as it only passes current session data when online.
So you will need to contact notion.so if you want that as they said I can not add it in.

**Comment by xzavrel** [comment]
It may be related with go off-line but it happens even when I'm on-line. It seems to be some "slow sync" issue or something like that. It happens independently of the connection type (wireless/lan), icmp ping notion.so < 18ms.
I notice the issue after some time of usage not immediately after lunch. But I haven't found any regular situation when it starts.

I use the app for at least 4 month and during the first 2 month of usage it didn't appear since some time it happens regularly.

Chrome: 75.0.3770.100, Node v10.15.2

**Comment by xzavrel** [comment]
I have opend Dev Tools and found this error. Do you also have similar in yours?

```
/opt/notion-1.0.5/app.asar/node_modules/electron-log/renderer.js:34 [15:37:41.581] Error: Error: ENOENT, dev-app-update.yml not found in /opt/notion-1.0.5/app.asar
    at notFoundError (ELECTRON_ASAR.js:108:19)
    at fs.readFile (ELECTRON_ASAR.js:536:16)
    at go$readFile (/opt/notion-1.0.5/app.asar/node_modules/graceful-fs/graceful-fs.js:85:14)
    at readFile (/opt/notion-1.0.5/app.asar/node_modules/graceful-fs/graceful-fs.js:82:12)
    at readFile (/opt/notion-1.0.5/app.asar/node_modules/universalify/index.js:5:67)
From previous event:
    at /opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:617:70
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:618:7)
    at Lazy.AppUpdater.configOnDisk (/opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:222:58)
    at Lazy.get value [as value] (/opt/notion-1.0.5/app.asar/node_modules/lazy-val/out/main.js:17:27)
    at /opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:505:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at AppImageUpdater.getUpdateInfoAndProvider (/opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:517:7)
    at /opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:524:35
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:550:7)
    at /opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:439:29
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:445:7)
    at AppImageUpdater.checkForUpdates (/opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:357:35)
    at /opt/src/desktop/main/autoUpdater.ts:105:23
    at step (/opt/notion-1.0.5/app.asar/main/autoUpdater.js:32:23)
    at Object.next (/opt/notion-1.0.5/app.asar/main/autoUpdater.js:13:53)
    at /opt/notion-1.0.5/app.asar/main/autoUpdater.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/notion-1.0.5/app.asar/main/autoUpdater.js:3:12)
    at pollForElectronUpdates (/opt/notion-1.0.5/app.asar/main/autoUpdater.js:96:12)
    at Object.<anonymous> (/opt/src/desktop/main/autoUpdater.ts:113:2)
    at Object.<anonymous> (/opt/notion-1.0.5/app.asar/main/autoUpdater.js:126:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/src/desktop/main/main.ts:29:1)
(anonymous) @ /opt/notion-1.0.5/app.asar/node_modules/electron-log/renderer.js:34
/opt/notion-1.0.5/app.asar/node_modules/electron-log/renderer.js:34 [15:37:41.583] { level: 'error',
  from: 'autoUpdater',
  type: 'autoUpdaterError',
  error:
   { Error: ENOENT, dev-app-update.yml not found in /opt/notion-1.0.5/app.asar
       at notFoundError (ELECTRON_ASAR.js:108:19)
       at fs.readFile (ELECTRON_ASAR.js:536:16)
       at go$readFile (/opt/notion-1.0.5/app.asar/node_modules/graceful-fs/graceful-fs.js:85:14)
       at readFile (/opt/notion-1.0.5/app.asar/node_modules/graceful-fs/graceful-fs.js:82:12)
       at readFile (/opt/notion-1.0.5/app.asar/node_modules/universalify/index.js:5:67)
   From previous event:
       at /opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:617:70
       at Generator.next (<anonymous>)
   From previous event:
       at AppImageUpdater.loadUpdateConfig (/opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:618:7)
       at Lazy.AppUpdater.configOnDisk (/opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:222:58)
       at Lazy.get value [as value] (/opt/notion-1.0.5/app.asar/node_modules/lazy-val/out/main.js:17:27)
       at /opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:505:52
       at Generator.next (<anonymous>)
       at runCallback (timers.js:696:18)
       at tryOnImmediate (timers.js:667:5)
       at processImmediate (timers.js:649:5)
   From previous event:
       at AppImageUpdater.getUpdateInfoAndProvider (/opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:517:7)
       at /opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:524:35
       at Generator.next (<anonymous>)
   From previous event:
       at AppImageUpdater.doCheckForUpdates (/opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:550:7)
       at /opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:439:29
       at Generator.next (<anonymous>)
       at runCallback (timers.js:696:18)
       at tryOnImmediate (timers.js:667:5)
       at processImmediate (timers.js:649:5)
   From previous event:
       at AppImageUpdater._checkForUpdates (/opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:445:7)
       at AppImageUpdater.checkForUpdates (/opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:357:35)
       at /opt/src/desktop/main/autoUpdater.ts:105:23
       at step (/opt/notion-1.0.5/app.asar/main/autoUpdater.js:32:23)
       at Object.next (/opt/notion-1.0.5/app.asar/main/autoUpdater.js:13:53)
       at /opt/notion-1.0.5/app.asar/main/autoUpdater.js:7:71
       at new Promise (<anonymous>)
       at __awaiter (/opt/notion-1.0.5/app.asar/main/autoUpdater.js:3:12)
       at pollForElectronUpdates (/opt/notion-1.0.5/app.asar/main/autoUpdater.js:96:12)
       at Object.<anonymous> (/opt/src/desktop/main/autoUpdater.ts:113:2)
       at Object.<anonymous> (/opt/notion-1.0.5/app.asar/main/autoUpdater.js:126:3)
       at Module._compile (internal/modules/cjs/loader.js:711:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
       at Module.load (internal/modules/cjs/loader.js:620:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
       at Function.Module._load (internal/modules/cjs/loader.js:551:3)
       at Module.require (internal/modules/cjs/loader.js:658:17)
       at require (internal/modules/cjs/helpers.js:20:18)
       at Object.<anonymous> (/opt/src/desktop/main/main.ts:29:1)
     cause:
      { Error: ENOENT, dev-app-update.yml not found in /opt/notion-1.0.5/app.asar
          at notFoundError (ELECTRON_ASAR.js:108:19)
          at fs.readFile (ELECTRON_ASAR.js:536:16)
          at go$readFile (/opt/notion-1.0.5/app.asar/node_modules/graceful-fs/graceful-fs.js:85:14)
          at readFile (/opt/notion-1.0.5/app.asar/node_modules/graceful-fs/graceful-fs.js:82:12)
          at readFile (/opt/notion-1.0.5/app.asar/node_modules/universalify/index.js:5:67)
          at tryCatcher (/opt/notion-1.0.5/app.asar/node_modules/bluebird/js/release/util.js:16:23)
          at ret (eval at makeNodePromisifiedEval (/opt/notion-1.0.5/app.asar/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:15:23)
          at /opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:617:70
          at Generator.next (<anonymous>)
          at Generator.tryCatcher (/opt/notion-1.0.5/app.asar/node_modules/bluebird/js/release/util.js:16:23)
          at PromiseSpawn._promiseFulfilled (/opt/notion-1.0.5/app.asar/node_modules/bluebird/js/release/generators.js:97:49)
          at /opt/notion-1.0.5/app.asar/node_modules/bluebird/js/release/generators.js:201:15
          at AppImageUpdater.loadUpdateConfig (/opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:618:7)
          at Lazy.AppUpdater.configOnDisk (/opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:222:58)
          at Lazy.get value [as value] (/opt/notion-1.0.5/app.asar/node_modules/lazy-val/out/main.js:17:27)
          at /opt/notion-1.0.5/app.asar/node_modules/electron-updater/out/AppUpdater.js:505:52 code: 'ENOENT', errno: -2 },
     isOperational: true,
     code: 'ENOENT',
     errno: -2 } }
```

**Comment by sysdrum** [comment]
I still can not work around this issue. Notion.so has refused to provide support for 3rd party.
